spring.application.name=BiteBeeFoodApplication
spring.datasource.url=jdbc:mysql://localhost:3306/havemore_db1
server.port=8080
spring.datasource.username=root
spring.datasource.password=Nagasai@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
